<div class="nav">
			<a href="index.php" id="0" onClick="nav_item_selected(0)">Home</a>
			<div class="dropdown">
				<button class="dropbtn" id="1">Rent</button>
				<div class="dropdown-content">
					<a href="apartment.html" onClick="nav_item_selected(1)">Apartment and Unit</a>
					<a href="house.html" onClick="nav_item_selected(1)">House</a>	
					<a href="townhouse.html" onClick="nav_item_selected(1)">Townhouse</a>	
					<a href="villa.html" onClick="nav_item_selected(1)">Villa</a>	
				</div>
			</div>
			<div class="dropdown">
				<button class="dropbtn" id="2">Homestay</button>
				<div class="dropdown-content">
					<a href="Homestay.html" onClick="nav_item_selected(2)">Home Parents</a>
					<a href="looking.html" onClick="nav_item_selected(2)">Looking a family</a>	
				</div>
			</div>
			<div class="dropdown">
				<button class="dropbtn" id="3">Communication Bar</button>
				<div class="dropdown-content">
					<a href="CommunicationBar.html" onClick="nav_item_selected(3)">Blackboard</a>
					<a href="Q&A.html" onClick="nav_item_selected(3)">Q and A</a>
				</div>
			</div>
			<div class="dropdown">
				<button class="dropbtn" id="4">Support</button>
				<div class="dropdown-content">
					<a href="notice.php" onClick="nav_item_selected(4)">Notice for Rent</a>	
					<a href="legalagent.html" onClick="nav_item_selected(4)">Legal Agent</a>
					<a href="agreement.html" onClick="nav_item_selected(4)">Agreement Model</a>
					<a href="secondhand.html" onClick="nav_item_selected(4)">Second Hand Requirement</a>
				</div>
			</div>
			<div class="dropdown">
				<button class="dropbtn" id="5">About Us</button>
				<div class="dropdown-content">
					<a href="AboutUs.html" onClick="nav_item_selected(5)">Contact Us</a>	
					<a href="achievement.html" onClick="nav_item_selected(5)">Achievements</a>
					<a href="link.html" onClick="nav_item_selected(5)">Link</a>
					<a href="partners.html" onClick="nav_item_selected(5)">Partners</a>
				</div>
			</div>
		</div>